FROM node:19-alpine

# Create app directory
WORKDIR /usr/src/app

# COPY package.json .
# COPY package-lock.json .
# RUN npm install 

# CMD ["npm", "start"]

# EXPOSE 4000

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

CMD ["npm", "start"]
EXPOSE 4000
