FROM node:19-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY src src
COPY icon icon
COPY public public
RUN npm run build

FROM nginx:1-alpine
COPY --from=builder /usr/src/app/build /frontend
COPY ./nginx-production.conf /etc/nginx/nginx.conf
