courts = {
    'Sierra Leone': 1715,
    None: 1527,
    'Zanzibar': 774,
    'St. Helena': 447,
    'Cape of Good Hope': 241,
    'Saint Helena': 209,
    'Mauritius': 134,
    'Havana': 114,
    'Tortola': 78,
    'Rio de Janeiro': 73,
    'Cape of Goode Hope': 57,
    'Loanda': 52,
    'Antigua': 48,
    'Havanna': 48,
    'Jamaica': 48,
    'Suakin': 39,
    'various': 31,
    'Rio de janeiro': 26,
    'Muscat': 26,
    'Rio de Janiero': 26,
    'Trinidad': 26,
    'Demerara': 24,
    'British & Protuguese Mixed Comission Court at Sierra Leone': 24,
    'Hamburg': 20,
    'St. Christopher': 19,
    'Bahamas': 18,
    'British & Portuguese Mixed Comission Court at Sierra Leone': 18,
    'British & Spanish Mixed Comission Court at Sierra Leone': 17,
    'Hong Kong': 16,
    'Sierre Leone': 15,
    'Aden': 14,
    'St. Lucia': 13,
    'High Court of Admiralty': 12,
    'Genoa': 11,
    'New York': 10,
    'Gambia': 10,
    'Bremen': 10,
    'St. Christophers': 9,
    'Dominica': 8,
    'St. Chrstophers': 8,
    'British & Spanish Mixed Comission Court': 8,
    'Seychelles': 7,
    'Mauritus': 7,
    'Cape Verde': 7,
    'Boa Vista': 6,
    'British Guiana': 6,
    'Bermuda': 6,
    'Barbadoes': 6,
    'Nassau': 6,
    'Unlisted': 6,
    'Gold Coast': 5,
    'England': 5,
    'Havannah': 5,
    'Rio De Janeiro': 5,
    'St. Kitts': 5,
    'British & Portuguese Mixed Comission Court': 5,
    'Cape of Good Hope.': 5,
    'Lagos': 4,
    'Port Royal': 4,
    'Rio De Janiero': 4,
    'St. Chrstopher': 4,
    'st. Helena': 4,
    'Bombay': 4,
    'Quebec': 3,
    'Virgin Islands': 3,
    'Seirra Leone': 3,
    'New Providence': 3,
    'Nevis': 3,
    'Briish & Spanish Mixed Comission Court at Sierra Leone': 3,
    'Vice Admiralty': 3,
    'Cape of good Hope': 3,
    'Netherlands': 3,
    'Spain': 3,
    'Madagascar': 3,
    'Mozambique': 2,
    'Cape of Good Hope, Havana, Jamaica, Sierra Leone': 2,
    'Port of Genoa': 2,
    'Cape of Good hope': 2,
    'Domingo': 2,
    'Portugal': 2,
    'Vice Admiralty of Sierra Leone': 2,
    'London': 2,
    'London (?)': 2,
    'St. Chistophers': 2,
    'Trinida': 2,
    'Tobago': 2,
    'Gibraltor': 2,
    'Charleston, Nevis': 2,
    'sierra Leone': 2,
    'British Spanish Mixed Comission Court at Sierra Leone': 2,
    'British Brazillain Mixed Comission Court at Rio de Janeiro': 2,
    'British Spanish Court of Mixed Comission': 2,
    'Admrialty Court': 2,
    'Vice Admiralty Court': 2,
    'Vice Admiralty Court at Sierra Leone': 2,
    'Bahia': 2,
    'Admiralty Court, New York': 2,
    'SIerra Leone': 2,
    'Bremenhaven': 2,
    'Sierra Leone, Saint Helena': 2,
    'Malta': 2,
    'Saint Helena (?)': 2,
    'St Helena': 2,
    'Mauritus/ Cape of Good Hope': 1,
    'Guiana': 1,
    'Equator': 1,
    'Jamiaca': 1,
    'Vice Admiralty of Dominica': 1,
    'Port Louis': 1,
    'Berbice': 1,
    '[Sierra Leone]': 1,
    'Sierra Lenoe': 1,
    'Jamaica (?)': 1,
    'St. Thomas': 1,
    'Ceylon': 1,
    'Diego Garcia': 1,
    '? (in W. Indies)': 1,
    'Montserrat': 1,
    'St. Kitts(?)': 1,
    'Havana(?)': 1,
    'Port of Scarborough and Tobago': 1,
    'St.Lucia': 1,
    'Grenada': 1,
    'Barbados Return': 1,
    'Sierra eonne': 1,
    'Quebec ees': 1,
    'Bahamasone': 1,
    'Cape Town': 1,
    'BahamasVice': 1,
    'Sierra eone': 1,
    'BahamasEnumeration': 1,
    'Bermuda, Bahamas': 1,
    'Nassau, Bahamas': 1,
    'Rio de Janeiro and Sierra Leone': 1,
    'Freetown': 1,
    'St. Chrisophers': 1,
    'Barbados': 1,
    'Nassua, Bahamas': 1,
    'St. Vincent': 1,
    'St.Christophers': 1,
    'British Spanish Mixed Comission Court': 1,
    'British Spanish? Mixed Comission Court at Havana': 1,
    'British Spanish Mixed Comission Court at ____': 1,
    'British Spanish Mixed Comission Court in Cuba': 1,
    'British Spanish Court of Mixed Comission at Sierra Leone': 1,
    'British & Spanish Court of Justice': 1,
    'British & Spanish & Portuguese Mixed Comission Courts at Sierra Leone': 1,
    'British & Portuguese Mixed Comission Courtat Sierra Leone': 1,
    'British & Brazillian Mixed Comission Court at Rioi de Janeiro': 1,
    'Mixed Comission Courts of Sierra Leone': 1,
    'British & Brazillian Mixed Comission Court': 1,
    'British & Protuguese Mixed Comission Court': 1,
    'British & Brazillian Mixed Comission Court at Sierra Leone': 1,
    'British & Spanish Mixed Comissin Court at Sierra Leone': 1,
    'British & Spanish mixed Comission Court': 1,
    'British & Spanish Mixed Comission Court at Havana (that Island)?': 1,
    'British & Spanish Mixed Comission Court at Havana': 1,
    'Vice Court of Admiralty at Lower Canada': 1,
    'British & Spanish Mixed Comission Court (likely at Havana)': 1,
    'British & Brazillian Mixed Comission Court at Rio de Janeiro': 1,
    'Maurititus': 1,
    'Portsmouth': 1,
    'Bayenne': 1,
    'Unknown': 1,
    'Court of Africa': 1,
    'Shelburne, Nova Scotia': 1,
    'Salem': 1,
    'rio De Janeiro': 1,
    'rio de Janeiro': 1,
    'Totola': 1,
    'Cape of Good Hope/ St. Helena': 1,
    '"British-Portuguese Commission Court"': 1,
    'Bremen (Germany?)': 1,
    'Kingston': 1,
    'Madrid': 1,
    'High Court of the Admiralty': 1,
    'Bordeaux': 1,
    'Sierra Leone, Loanda, Havana': 1,
    'Hamburg (?)': 1,
    'Bathurst': 1,
    'Porto Rico': 1,
    'not given': 1,
    'Washington': 1,
    'St. elena': 1,
    'Zanzibar/ Aden': 1,
    'Muscat/ Aden': 1
}

mixed = {
    None: 2821, 
    'no': 827,
    'British Vice Admiralty Court': 368,
    'British vice Admiralty Court': 239,
    'British Mixed Commisions Court': 161,
    'yes': 148,
    'yes, Spanish': 110,
    'British and Spanish Mixed Commisions Court': 106,
    'Yes': 105,
    'British and Brazilian Mixed Commisions Court': 86,
    'Vice Admiralty Court': 85,
    'British Mixed commisions court': 79,
    'yes, British and Spanish': 67,
    'yes, Brazilian': 58,
    'yes, English/Spanish': 55,
    'yes, British and Brazillian': 48,
    'Yes, Spanish': 46,
    'yes, Portuguese': 45,
    'Vice Admiralty': 42,
    'British and Portuguese Mixed Commisions Court': 40,
    'yes Portuguese': 38,
    'British Mixed Commision Court': 36,
    'British and Spanish Mixed Commisions court': 31,
    'yes, Brazil': 30,
    'yes Spanish': 24,
    'Yes, British/Portuguese': 23,
    'British and Brazilian Mixed commisions court': 22,
    'yes, Dutch': 21,
    'Yes, Brazilian': 21,
    'British and Portuguese Mixed commisions Court': 20,
    'Yes, British and Spanish Mixed Commisions Court': 20,
    'some': 19,
    'Vice-Admiralty': 17,
    'Yes, British/Spanish': 16,
    'yes Dutch': 16,
    'yes, Britsh Vice Admiralty court': 16,
    'Yes, British Vice Admiralty Court': 16,
    'Yes, Vice Admiralty Court  St. Helena': 13,
    'British and Brazilian Mixed commisions Court': 12,
    'yes, Vice Admiralty court St. Helena': 12,
    'British and Portuguese Mixed Commision Court': 11,
    'yes, British and Portuguese': 11,
    'Yes, British and Brazilian Mixed Commisions Court': 11,
    'British Liberated African Department': 10,
    'British and Portuguese Mixed commision Court': 10,
    'British Mixed Commisions': 10,
    'Court of Vice Admirality': 10,
    'British and Spanish Mixed commisions': 10,
    'Yes, Portuguese': 10,
    'No': 9,
    'Mixed Commisions': 9,
    'Custom House': 9,
    'yes, English/Brazilian': 9,
    'Yes, British and Brazilian Court of Mixed Commisions': 9,
    'N/A': 8,
    'Yes; Spanish': 8,
    'British Vice Admiralty court': 7,
    'Yes, English/Spanish': 7,
    'British and Portuguese  Mixed commisions': 7,
    'yes, English/Portugese': 7,
    'Yes, British and Brazilian Mixed Commisions Court.': 7,
    'Yes, Portugese': 6,
    'Yes, Vice Admiralty court, Cape of Good Hope': 6,
    'British and Netherlands Mixed Commision court': 5,
    'British and Portuguese Mixed commisions court': 5,
    'Yes, English/Portuguese': 5,
    'yes British/Spanish': 5,
    'Vice Admiralty court': 5,
    'yes, Vice Admiralty Court, Sierra Leone': 5,
    'British and Spanish Mixed Commisions Courft': 4,
    'Yes, British/Netherlands': 4,
    'yes, Portugual': 4,
    'Yes; Brazilian': 4,
        'yes, English/Portuguese': 4,
    'British and Portuguese Mixed Commisions': 4,
    'British and Portuguese mixed commisions court': 4,
    'Customs House': 4,
    'Yes, Vice Admiralty Court Cape of Good Hope': 4,
    'yes, Brtish and Brazilian mixed commisions court at Rio De Janiero': 4,
    'Yes, British Brazialian Mixed commisions court Sierra Leone': 4,
    'British and Spanish Mixed commisions court': 3,
    'Vice Admiralty, Cape of Good Hope': 3,
    'Yes, British Portuguese  Mixed commisions court Sierra Leone': 3,
    'British and Netherlands Mixed commisions court': 2,
    'British and Spanish Mixed Commision Court': 2,
    'British and Spanish Mixed commisions Court': 2,
    'Briish Mixed Commisions Court': 2,
    'British and French Mixed Commisions Court': 2,
    'Yes, English/Netherlands': 2,
    'Vice Admirality Court': 2,
    'Yes, Spanish, Portugese, and Netherlands': 2,
    'British custom House': 2,
    'British and Brazlian Mixed commisions court': 2,
    'Yes, British and Portuguese Mixed Commisions Court': 2,
    'Yes, Vice Admiralty Court Sierra Leone': 2,
    'yes, Sierra Leone Mixed Commisions': 2,
    'Yes, British and Portuguese Mixed Commisions court': 2,
    'Yes, Zanzibar': 2,
    'Portugal': 2,
    'British and United Stated Mixed Commisions Court': 1,
    'British Liberated African department': 1,
    'British and Brazilian Mixed Commisions court': 1,
    'yes British/Dutch': 1,
    'yes British/Portuguese': 1,
    'yes? Portuguese': 1,
    '22 September 1829': 1,
    'No(?)': 1,
    'Yes; Spanish(?)': 1,
    'Yes, French': 1,
    'Vice Admirality Court of New Providence': 1, "Colonial Secretary's Office, Liverpool": 1,
    'Court of Admirality': 1,
    'Spanish & British Mixed Commisions': 1,
    'British and Brazilian Mixed commisions': 1,
    'High Court of Admiralty': 1,
    'British and Spanish Mixed Commisions': 1,
    'British and Spanish': 1,
    'yes, Spanish and British': 1,
    'Vice Admiralty, Sierra Leone': 1,
    'yes, Spanish and Brazillian': 1,
    'Government House Dominica': 1,
    'yes, British and Portuguese Mixed Commisions Court': 1,
    'Yes, Vice Admiralty Court Barbadoes': 1,
    'Britsh Vice Counsel at Bremen': 1,
    'Yes, British and Spanish': 1,
    'yes, Cape of Good Hope': 1,
    'yes, Vice Admiralty Court, St. Helena': 1,
    'yes, Vice Admiralty Mauritius': 1,
    'Yes, HMS court at New york': 1,
    'YEs, British Vice Admiralty Court': 1,
    'Yes, British and Spanish Mixed Commisions court': 1,
    'Yes, British and Portuguese Court of Mixed Commisions': 1,
    'yes?': 1,
    'French': 1,
    'Portuguese': 1,
    'France': 1,
    'Yes - Egypt': 1
}
